//
//  PWZoneEventManager.h
//  PWLocalpoint
//
//  Copyright (c) 2015 Phunware, Inc. All rights reserved.
//

#import "PWLPZoneManagerProtocol.h"
#import "PWLPZoneEventNotifications.h"

@protocol PWLPZoneEventManagerDelegate;

/**
 * A zone manager used to forward the zone events generated by the Location Marketing service to its delegate. 
 */
@interface PWLPZoneEventManager : NSObject <PWLPZoneManager>

/**
 * The available geozones handled by the zone manager.
 * @discussion This zone manager does not handle any zones so the available zones will always be `nil`.
 */
@property (nonatomic, readonly) NSArray *availableZones;

/**
 * The zones currently being monitored by the zone manager.
 * @discussion This zone manager does not handle any zones so the monitored zones will always be `nil`.
 */
@property (nonatomic, readonly) NSArray *monitoredZones;

/**
 * Starts the zone manager.
 */
- (void)start;

/**
 * Stops the zone manager.
 */
- (void)stop;

/**
 * The delegate object that will receive the callbacks defined in the `PWLPZoneManagerDelegate` protocol.
 */
@property (nonatomic, weak) id<PWLPZoneManagerDelegate> delegate;


@end
